# Generated by Django 6.0.3 on 2026-03-18 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_categoria_remove_tarefa_concluida_tarefa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarefas.categoria'),
        ),
    ]
