# Generated by Django 6.0.3 on 2026-03-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('completa', 'Completa'), ('cancelada', 'Cancelada'), ('perdida', 'Perdida')], default='ativa', max_length=20),
        ),
    ]
